// import chalk from 'chalk';

// console.log(chalk.black('black:Hello world!'));
// console.log(chalk.red('red:Hello world!'));
// console.log(chalk.green('green:Hello world!'));
// console.log(chalk.yellow('yellow:Hello world!'));
// console.log(chalk.blue('blue:Hello world!'));
// console.log(chalk.magenta('magenta:Hello world!'));
// console.log(chalk.cyan('cyan:Hello world!'));
// console.log(chalk.white('white:Hello world!'));
// console.log(chalk.blackBright('blackBright:Hello world!'));
// console.log(chalk.redBright('redBright:Hello world!'));
// console.log(chalk.greenBright('greenBright:Hello world!'));
// console.log(chalk.yellowBright('yellowBright:Hello world!'));
// console.log(chalk.blueBright('blueBright:Hello world!'));
// console.log(chalk.magentaBright('magentaBright:Hello world!'));
// console.log(chalk.cyanBright('cyanBright:Hello world!'));
// console.log(chalk.whiteBright('whiteBright:Hello world!'));

// console.log(chalk.bgBlack('bgBlack:Hello world!'));
// console.log(chalk.bgRed('bgRed:Hello world!'));
// console.log(chalk.bgGreen('bgGreen:Hello world!'));
// console.log(chalk.bgYellow('bgYellow:Hello world!'));
// console.log(chalk.bgBlue('bgBlue:Hello world!'));
// console.log(chalk.bgMagenta('bgMagenta:Hello world!'));
// console.log(chalk.bgCyan('bgCyan:Hello world!'));
// console.log(chalk.bgWhite('bgWhite:Hello world!'));
// console.log(chalk.bgBlackBright('bgBlackBright:Hello world!'));
// console.log(chalk.bgRedBright('bgRedBright:Hello world!'));
// console.log(chalk.bgGreenBright('bgGreenBright:Hello world!'));
// console.log(chalk.bgYellowBright('bgYellowBright:Hello world!'));
// console.log(chalk.bgBlueBright('bgBlueBright:Hello world!'));
// console.log(chalk.bgMagentaBright('bgMagentaBright:Hello world!'));
// console.log(chalk.bgCyanBright('bgCyanBright:Hello world!'));
// console.log(chalk.bgWhiteBright('bgWhiteBright:Hello world!'));

// console.log(chalk.bold('bold:Hello world!'));
// console.log(chalk.italic('italic:Hello world!'));
// console.log(chalk.underline('underline:Hello world!'));
// console.log(chalk.inverse('inverse:Hello world!'));
// console.log(chalk.strikethrough('strikethrough:Hello world!'));
// console.log(chalk.dim('dim:Hello world!'));
// console.log(chalk.reset('reset:Hello world!'));
// console.log(chalk.visible('visible:Hello world!'));
// console.log(chalk.hidden('hidden:Hello world!'));
